POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "testTitle5",
    "author": "Tester5",
    "url": "www.Testurl5.com",
    "likes": 5,
    "userId": "61e759e2eff4bdbfae07bb43"
}