POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2MWU3NWEzOWVmZjRiZGJmYWUwN2JiNDYiLCJpYXQiOjE2NDMxMjU3NjJ9.nT-yOU6CvPMCOgZby2pKDR7jTGgGqs1tSB5gRjE1mqA

{
    "title": "testTitle1234",
    "author": "Tester1234",
    "url": "www.Testurl234.com",
    "likes": 555
}